### ISSUE TITLE
D2 - Diagrams

### ISSUE THREAD

**Issue by tjosepo** [tommy-josepovic/smarthome-simulator#44]
Diagrams include:

- Update class diagram with the new classes implemented
- Sequence diagram (1 for each new use case)  Remember to write the use cases using essential style and at User-goal level.
- State-machine diagram for the House view
- Activity diagram for Smart home security module

**Comment by RonickUch** [comment]
- [x] Update class diagram
- [x] Sequence diagram
- [x] State-machine diagram
- [x] Activity diagram

**Comment by RonickUch** [comment]
I'm currently working on the Activity and state-machine diagrams.

**Comment by RonickUch** [comment]
Diagrams are completed and inserted inside the report.
